name: Check Dependencies

on:
  schedule:
    - cron: '0 0 * * *'  # Uruchom codziennie o północy

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check for outdated dependencies
        run: |
          outdated=$(pip list --outdated)
          if [ -n "$outdated" ]; then
            echo "Znaleziono przestarzałe zależności:"
            echo "$outdated"
            exit 1
          else
            echo "Wszystkie zależności są aktualne."
          fi
