name: Create New Branch

on:
  create:
    branches:
      - '*'

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create new branch
        run: |
          git checkout -b new-branch-${{ github.event.ref }}
          git push origin new-branch-${{ github.event.ref }}
