name: Welcome Message

on:
  issues:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome message
        run: |
          echo "Witaj w moim repozytorium! "
